modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "create_tram_additions"
version = "${version}"
displayName = "Create Tram Additions"
authors = "qliqs"
description = '''
A mod that adds on-board announcements on the trains.
'''
logoFile = "tramadditions.png"

[[dependencies.create_tram_additions]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_tram_additions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_tram_additions]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_tram_additions]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_tram_additions]]
modId="createrailwaysnavigator"
mandatory = false
versionRange = "[1.20.1-0.5.5,)"
ordering="NONE"
side="BOTH"